### PR TITLE
update minimist

### PR DESCRIPTION
**Pull request by ralphtheninja**
`rc` is using an old version of `minimist` and I'd like to be able to use minimist aliases, e.g.

```js
var minimist = require('minimist')

module.exports = require('rc')('myapp', {
  foo: 'foovalue',
  bar: 'barvalue'
}, minimist(process.argv, {
  alias: { foo: 'f', bar: 'b' }
}))
```

While I can always do this it's nice if rc uses the latest minimist so npm can dedupe properly whenever a dependant depends on both rc and minimist.

Alternatively I'd like to be able to somehow pass the aliases object into rc which in turn passes it to minimist.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Basically it's the dedupe step I'm after :)

**Comment by dominictarr** [comment]
okay cool

**Comment by dominictarr** [comment]
i decided that the correct thing to do is make this a minor change.
merged into 1.1.0

**Comment by ralphtheninja** [comment]
:+1:

**Pull request merged**
