### PR TITLE
Bump deep-extend to 0.5.0

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by realityking** [comment]
@dominictarr Could you review this one?

**Comment by dominictarr** [comment]
you didn't tell my why deep-extend needs to be upgraded

**Comment by realityking** [comment]
@dominictarr Sorry about that. `deep-extend` 0.5.0 is a very minor update ([Diff](https://github.com/unclechu/node-deep-extend/compare/v0.4.2...v0.5.0)) that essentially just removes the tests from the package. I'd like to see it updated so it can deduplicate with other dependencies that require version 0.5.

**Comment by macpham** [comment]
It would be nice if it wen to `0.5.1` or greater actually because of: https://nodesecurity.io/advisories/612

**Comment by gustawdaniel** [comment]
Any info about status of this update?

I am asking because of vulnerability mentioned by @macpham 

Is is enough to change version of deep-extend to `0.5.1` or there is more work to do?

**Comment by gustawdaniel** [comment]
I found

> https://github.com/dominictarr/rc/commit/73f285bb1f749331eaeab6c41f4505f90fe4ac35

So this pull request and discuss can be closed. It would be nice if GitHub releases could be identical like Npm releases. Any way thank you for update :)

**Pull request closed without merging**
