### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by TrySound**
To reduce dep tree

### CODE REVIEW

**Comment by dominictarr** [comment]
Strip-json-comments goes to version 1. Is that a breaking change?

**Comment by TrySound** [comment]
@dominictarr Nope, just semver

**Comment by dominictarr** [comment]
merged into 1.1.3

**Comment by TrySound** [comment]
@dominictarr I accidentally reduced minimist version by adding tilde indead of caret. Maybe need to use caret for all dependencies?

**Comment by dominictarr** [comment]
just keep the things that are tilde on tilde and the things that are caret
on caret

**Pull request merged**
