### PR TITLE
Changes `config` key to point to latest parsed config file instead of only .namerc if it exists

### PR DESCRIPTION
**Pull request by secrettriangle**
Also adds `configs` key that contains all config files loaded

### CODE REVIEW

**Comment by secrettriangle** [comment]
@dominictarr @achingbrain can we get this merged? I think everyone can agree with these changes.

**Comment by dominictarr** [comment]
@secrettriangle oh, sorry, can you add documentation and a test? then I'll merge

**Comment by secrettriangle** [comment]
@dominictarr done!

**Comment by dominictarr** [comment]
thank you @secrettriangle 
merged into 1.0.0, since the config property has changed.

**Comment by dominictarr** [comment]
although, it probably doesn't break (m)any programs.

**Pull request merged**
